#!/bin/bash

# Disk Cleanup Script
# Generated by AI Assistant

echo "Starting disk cleanup..."
echo "--------------------------------"

# 1. Delete Etude Project (~9.4 GB)
if [ -d "/Users/xixiaohai/code/Etude" ]; then
    echo "Deleting Etude project..."
    rm -rf "/Users/xixiaohai/code/Etude"
else
    echo "Etude project not found, skipping."
fi

# 2. Delete WeChat Data (~24 GB)
# User confirmed WeChat is uninstalled.
if [ -d "/Users/xixiaohai/Library/Containers/com.tencent.xinWeChat" ]; then
    echo "Deleting WeChat data..."
    rm -rf "/Users/xixiaohai/Library/Containers/com.tencent.xinWeChat"
else
    echo "WeChat data not found, skipping."
fi

# 3. Delete Maxon/Cinema 4D Preferences (~5.3 GB)
# This removes the large preferences folder found.
if [ -d "/Users/xixiaohai/Library/Preferences/Maxon" ]; then
    echo "Deleting Maxon preferences..."
    rm -rf "/Users/xixiaohai/Library/Preferences/Maxon"
else
    echo "Maxon preferences not found, skipping."
fi

# 4. Clean NPM Cache (~7.7 GB)
echo "Cleaning NPM cache..."
npm cache clean --force

echo "--------------------------------"
echo "Cleanup complete!"
echo "Current disk usage for /:"
df -h /
