#!/bin/bash

# Desktop Organization Script
# Generated by AI Assistant

DESKTOP_PATH="/Users/xixiaohai/Desktop"
SCREENSHOTS_DIR="$DESKTOP_PATH/Screenshots"
FILES_DIR="$DESKTOP_PATH/Files"

echo "Starting Desktop organization..."
echo "--------------------------------"

# Create directories if they don't exist
if [ ! -d "$SCREENSHOTS_DIR" ]; then
    mkdir -p "$SCREENSHOTS_DIR"
    echo "Created directory: Screenshots"
fi

if [ ! -d "$FILES_DIR" ]; then
    mkdir -p "$FILES_DIR"
    echo "Created directory: Files"
fi

# Move Screenshots (matching "截屏" or "Screenshot")
# Using find to avoid errors if no files match
find "$DESKTOP_PATH" -maxdepth 1 -name "截屏*.png" -print0 | xargs -0 -I {} mv {} "$SCREENSHOTS_DIR/" 2>/dev/null
find "$DESKTOP_PATH" -maxdepth 1 -name "Screenshot*.png" -print0 | xargs -0 -I {} mv {} "$SCREENSHOTS_DIR/" 2>/dev/null
echo "Moved screenshots to $SCREENSHOTS_DIR"

# Move other loose files to Files (excluding directories and the script itself)
# We explicitly list extensions we saw or generic catch-all for files
mv "$DESKTOP_PATH"/*.json "$FILES_DIR/" 2>/dev/null
mv "$DESKTOP_PATH"/*.jsonl "$FILES_DIR/" 2>/dev/null
mv "$DESKTOP_PATH"/*.pdf "$FILES_DIR/" 2>/dev/null
# Add more generic move if needed, but safer to be specific or ask. 
# User asked to organize "a bit", so acting on known loose files is good.

echo "Moved .json, .jsonl, .pdf to $FILES_DIR"

echo "--------------------------------"
echo "Organization complete!"
echo "Your Desktop now contains folders: Screenshots, Files, and your existing folders."
